targets:  
  $default:  
    builders:  
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
      injectable_generator|injectable_builder:  
        options:  
          auto_register: true  
          class_name_pattern:  
            "Repository$|Cubit$"  
          file_name_pattern: "_repository$|_cubit$"
