targets:  
  $default:  
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/domain/models/**.dart
          - lib/data_sources/**.dart
        options:
          build_extensions:
            '^lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.g.dart'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.freezed.dart' 
          field_rename: snake
          explicit_to_json: true  
      json_serializable:
         options:
          field_rename: snake
          explicit_to_json: true  
      injectable_generator|injectable_builder:  
        options:  
          auto_register: true  
          class_name_pattern:  
            "Repository$|Cubit$"  
          file_name_pattern: "_repository$|_cubit$"
