// final categories = <String>[
//   "Random"
//       "General Knowledge",
//   "Entertainment: Books",
//   "Entertainment: Film",
//   "Entertainment: Music",
//   "Entertainment: Musicals & Theatres",
//   "Entertainment: Television",
//   "Entertainment: Video Games",
//   "Entertainment: Board Games",
//   "Entertainment: Japanese Anime & Manga",
//   "Entertainment: Cartoon & animations",
//   "Entertainment: Comics",
//   "Science & Nature",
//   "Science: Computers",
//   "Science: Mathematics",
//   "Science: Gadgets",
//   "Mythology",
//   "Sports",
//   "Geography",
//   "History",
//   "Politics",
//   "Art",
//   "Celebrities",
//   "Animals",
//   "Vehicles",
// ];
